#!/usr/bin/env python
import argparse
from app import SetlistData, phish_net_client as client
from datetime import datetime

parser = argparse.ArgumentParser()
parser.add_argument('--update', default='all',
                    choices=['all', 'year'], help='download all data or current year')
parser.add_argument('--year',  type=int, default=None,
                    help="Year to update if update = 'year'")
args = parser.parse_args()


def create_all():
    print("Updating all...")
    setlist_data = SetlistData(client.download_all())
    setlist_data.save_all()
    setlist_data.save_years()


def create_year(year=None):
    if year == None:
        year = datetime.now().year

    print(f"Updating year {year}...")
    setlist_data = SetlistData(client.get_setlist_data(year))
    setlist_data.save_years()


if args.update == 'year':
    create_year(args.year)
elif args.update == 'all':
    create_all()
